-- ---------------------------------------------------------------------- -
-- 1. BEISPIEL: UNION KLAUSEL
-- ---------------------------------------------------------------------- -
-- REGION

-- FINDEN SIE ALLE KAPITÄNE DIE AUF KREUZFAHRTEN BESCHÄFTIGT HABEN. GEBEN SIE
-- ZUSÄTZLICH ALLE 1 MATE AUS DIE AUF EINEM FLUGZEUGTRÄGER GEDIENT HABEN.

-- AUSGABE: FIRST_NAME, LAST_NAME

-- TABELLEN: EMPLOYEE_ST, CRUISE_HAS_EMPLOYEES_JT

SELECT DISTINCT FIRST_NAME, LAST_NAME
FROM EMPLOYEE_ST E
         JOIN CRUISE_HAS_EMPLOYEES_JT CHEJ ON E.EMPLOYEE_ID = CHEJ.EMPLOYEE_ID
WHERE CHEJ.EMPLOYEE_ROLE = 'CAPITAIN'
UNION
SELECT DISTINCT FIRST_NAME, LAST_NAME
FROM EMPLOYEE_ST E
         JOIN CRUISE_HAS_EMPLOYEES_JT CHEJ ON E.EMPLOYEE_ID = CHEJ.EMPLOYEE_ID
         JOIN CRUISES C ON CHEJ.CRUISE_ID = C.CRUISE_ID
         JOIN SHIPS S on C.SHIP_ID = S.SHIP_ID
WHERE CHEJ.EMPLOYEE_ROLE = '1_MATE'
  AND S.SHIP_CLASSIFICATION = 'AIRCRAFT_CARRIER';



-- ENDREGION


-- ---------------------------------------------------------------------- -
-- 2. BEISPIEL: UNION KLAUSEL
-- ---------------------------------------------------------------------- -
-- REGION

-- FINDEN SIE ALLE KREUZFAHRTEN, DIE IN EINEM UBOOT STATTFINDEN BZW. DIE
-- ZUMINDESTENS EINEN HAFEN IN ITALIEN ANFAHREN.

-- AUSGABE: CRUISE_ID, LABEL


-- TABELLEN: CRUISES, SHIPS, CRUISE_HAS_ROUTES_JT, HARBORS

SELECT C.CRUISE_ID, C.LABEL
FROM CRUISES C
         JOIN SHIPS S ON C.SHIP_ID = S.SHIP_ID
WHERE S.SHIP_CLASSIFICATION = 'AIRCRAFT_CARRIER'
UNION
SELECT DISTINCT C.CRUISE_ID, C.LABEL
FROM CRUISES C
         JOIN CRUISE_HAS_ROUTES_JT CHRJ ON C.CRUISE_ID = CHRJ.CRUISE_ID
         JOIN HARBORS H ON H.HARBOR_ID IN (CHRJ.ARRIVAL_HARBOR_ID, CHRJ.DEPARTURE_HARBOR_ID)
WHERE H.COUNTRY = 'ITALY';



-- ENDREGION


-- ---------------------------------------------------------------------- -
-- 3. BEISPIEL: UNION, EXISTS KLAUSEL
-- ---------------------------------------------------------------------- -
-- REGION

-- FINDEN SIE ALLE KREUZFAHRTEN  DIE NUR HÄFEN AUF DEM EUROPÄISCHEN KONTINENT
-- ANFAHREN BZW. NUR HÄFEN AUF DEM ASIATISCHEN KONTINENT ANFAHREN.

-- AUSGABE: CRUISE_ID, LABEL

-- TABELLEN: CRUISES, CRUISE_HAS_ROUTES_JT, HARBORS

select C.CRUISE_ID, C.LABEL
from CRUISES C
where not exists(select *
             from CRUISE_HAS_ROUTES_JT CHRJ
                      join HARBORS H on H.HARBOR_ID in (CHRJ.DEPARTURE_HARBOR_ID, CHRJ.ARRIVAL_HARBOR_ID)
             where CHRJ.CRUISE_ID = C.CRUISE_ID
               AND H.CONTINENT != 'EUROPE')
union
select C.CRUISE_ID, C.LABEL
from CRUISES C
where not exists(select *
             from CRUISE_HAS_ROUTES_JT CHRJ
                      join HARBORS H on H.HARBOR_ID in (CHRJ.DEPARTURE_HARBOR_ID, CHRJ.ARRIVAL_HARBOR_ID)
             where CHRJ.CRUISE_ID = C.CRUISE_ID
               AND H.CONTINENT != 'ASIA');

select * from CRUISES C join CRUISE_HAS_ROUTES_JT CHRJ on C.CRUISE_ID = CHRJ.CRUISE_ID;


-- ENDREGION

-- ---------------------------------------------------------------------- -
-- 4. BEISPIEL: UNION, MINUS, INTERSECT, EXCEPT KLAUSEL
-- ---------------------------------------------------------------------- -
-- REGION

-- FINDEN SIE ALLE KREUZFAHRTEN DIE WEDER IN EINEM UBOOT NOCH IN EINEM
-- FLUGZEUGTRÄGER DURCHGEFÜHRT WERDEN. DIE KREUZFAHRTEN MÜSSEN ZUMINDESTENS
-- EINEN HAFEN IN EUROPA ANFAHREN.

-- AUSGABE: CRUISE_ID, LABEL

-- TABELLEN: CRUISES, CRUISE_HAS_ROUTES_JT, HARBORS, SHIPS






