SELECT PB.PROJECT_ID, PB.TITLE, PB.CREATED_AT, STATE_CHANGED_AT, STATE_CHANGED_AT - PB.CREATED_AT AS DAY_COUNT
FROM PROJECTS_BT PB
         JOIN PROJECT_HAS_STATES_JT PHSJ ON PB.PROJECT_ID = PHSJ.PROJECT_ID
WHERE NOT EXISTS(SELECT *
                 FROM PROJECT_HAS_STATES_JT PHSJ2
                 WHERE PHSJ.PROJECT_ID = PHSJ2.PROJECT_ID
                   AND PHSJ.STATE_CHANGED_AT < PHSJ2.STATE_CHANGED_AT)
  AND NOT EXISTS(SELECT * FROM SUBPROJECTS S WHERE S.PROJECT_ID = PB.PROJECT_ID)
UNION
SELECT PB.PROJECT_ID, PB.TITLE, PB.CREATED_AT, STATE_CHANGED_AT, STATE_CHANGED_AT - PB.CREATED_AT AS DAY_COUNT
FROM PROJECTS_BT PB
         JOIN SUBPROJECTS S ON PB.PROJECT_ID = S.PROJECT_ID
         JOIN SUBPROJECT_HAS_STATES_JT J ON S.SUBPROJECT_ID = J.SUBPROJECT_ID
WHERE NOT EXISTS(SELECT *
                 FROM SUBPROJECT_HAS_STATES_JT SHSJ
                 WHERE S.SUBPROJECT_ID = SHSJ.SUBPROJECT_ID
                   AND EXISTS(SELECT *
                              FROM SUBPROJECT_HAS_STATES_JT SHSJ2
                              WHERE SHSJ.SUBPROJECT_ID = SHSJ2.SUBPROJECT_ID
                                AND SHSJ.STATE_CHANGED_AT < SHSJ2.STATE_CHANGED_AT));