namespace Domain.Dishes; 

public enum EIngredient {
    TOMATOE, ONION, SALT, WATER, CREAM, PEPPER,
    PUMPKIN, CELERY, CARROT, BROTH, GARLIC, VEAL, 
    FLOUR, BREAD_CRUMBS, EGG, MILK, BUTTER, LEMON,
    OIL, MUSHROOM, SHALLOT, WINE, CHIVES, CHEESE,
    BACON, EGG_YOLK, PARMESAN_CHEESE, PASTA
}