FROM mcr.microsoft.com/dotnet/runtime:7.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["PdfGenerator/PdfGenerator.csproj", "PdfGenerator/"]
COPY ["Model/Model.csproj", "Model/"]
RUN dotnet restore "PdfGenerator/PdfGenerator.csproj"
COPY . .
WORKDIR "/src/PdfGenerator"
RUN dotnet build "PdfGenerator.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PdfGenerator.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PdfGenerator.dll"]
