version: '3'
name: 'ndfa-backend'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 'ndfa'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql_data:
